// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc5122.Fred.Robot;

/**
 *
 */
public class Auto extends CommandGroup {
    
    public  Auto() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
////        Robot.drivetrain.setSafetyEnabled(false);
////            System.out.println("Starting Autonomous Mode");
////        addSequential(new Drive(4.25, .5, 0));     //drive to goal
////            System.out.println("At Goal");
////        addSequential(new ThrowBall());         //throw ball
////            System.out.println("Ball Thrown");
////        //addSequential(new ArmToggle(false));    //put arm up
////        //System.out.println("Arm Is Up");
////        addSequential(new PullBackThrower(), 4);
////        addSequential(new Drive(5.25, -.5, 0), 5); //drive back to start
////        addParallel(new PullBackThrower(), 4);
////        
////            System.out.println("At Start & Thrower Back");
////        addSequential(new ArmToggle(false));    //put arm up
////            System.out.println("Arm Is Up");
////        addSequential(new Drive(4.75, .5, 0));     //drive to goal
////        addSequential(new PullBackThrower(), 4);
////            System.out.println("At Goal");
////        addSequential(new ThrowBall());         //throw ball
////            System.out.println("Ball Thrown");
////            System.out.println("Stop");
            
        //Auto #2 -- working
//		addSequential(new Debug("Starting Autonomous"));
//		addParallel(new DelayedArmDown(1));         //wait for the given time then put the arm down
//		addSequential(new Drive(2.5, .75, 0));      //drive to goal
//		addSequential(new Debug("At Goal"));
//		addSequential(new ThrowBallFast());
//		addParallel(new PullBackThrower());		//this really shouldn't be needed
//		addSequential(new Drive(2.75, -.75, 0));    //drive to pickup second ball
//		addSequential(new Debug("Picking Up Seconmd Ball"));
//		addSequential(new Drive(2.5, .75, 0));	//drive to goal
//		addSequential(new Debug("At Goal 2"));
//		addSequential(new ThrowBallFast());
//		addParallel(new PullBackThrower());		//this really shouldn't be needed
//		addSequential(new Debug("Done"));
		
		//Auto #3 -- Do auto #2 faster (less time)
//		addSequential(new Debug("Starting Autonomous"));
//		addParallel(new DelayedArmDown(1));         //wait for the given time then put the arm down
//		addSequential(new Drive(1.5, .75, 0));      //drive to goal //time, move, turn
//		addSequential(new Debug("At Goal"));
//		addSequential(new ThrowBallFast());
//		addParallel(new PullBackThrower());		//this really shouldn't be needed
//		addSequential(new Drive(2, -.75, 0));    //drive to pickup second ball
//		addSequential(new Debug("Picking Up Seconmd Ball"));
//		addSequential(new Drive(2, .75, 0));	//drive to goal
//		addSequential(new Debug("At Goal 2"));
//		addSequential(new ThrowBallFast());
//		addParallel(new PullBackThrower());		//this really shouldn't be needed
//		addSequential(new Debug("Done"));
		
		double speed = .6;
                double time2goal = 3;
		//Auto 4 -- Faster more time less speed
		addSequential(new Debug("Starting Autonomous"));
		addParallel(new DelayedArmDown(0));         //wait for the given time then put the arm down
		addSequential(new Drive(time2goal, speed, 0));      //drive to goal //time, move, turn
		addSequential(new Debug("At Goal"));
		addSequential(new ThrowBallFast());
		addSequential(new PullBackThrower());		//this really shouldn't be needed
//		addSequential(new Drive(time2goal+.5, speed*-1, 0));    //drive to pickup second ball
//		addSequential(new Debug("Picking Up Seconmd Ball"));
//		addSequential(new Drive(time2goal+1, speed, 0));	//drive to goal
//		addSequential(new Debug("At Goal 2"));
//		addSequential(new ThrowBallFast());
//		addParallel(new PullBackThrower());		//this really shouldn't be needed
		addSequential(new Debug("Done"));
        
    }
}
