// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc5122.Fred.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5122.Fred.Robot;
/**
 *
 */
public class  ThrowBallFast extends Command {
    private double start = 0;
    private boolean finished = false;
    private final double delay = .125;
    public ThrowBallFast() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.thrower);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        
    }
    // Called just before this Command runs the first time
    protected void initialize() {
		start = timeSinceInitialized();
        Robot.thrower.Throw();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        //if the kicker is still ready we havn't run long enough
        //make sure the kicker runs for at least delay seconds
        if (timeSinceInitialized()-start > delay) //!Robot.thrower.Ready() && 
		{
            finished = true;
			Robot.thrower.Stop();
        }
        
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return finished;
    }
    // Called once after isFinished returns true
    protected void end() {
        Robot.thrower.Stop();
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
