// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc5122.Fred.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5122.Fred.Robot;
import org.usfirst.frc5122.Fred.RobotMap;
/**
 *
 */
public class  WaitForCheesy extends Command {
	private double delay;
	private double start;
	private final int MIN_COUNT = 3;
    public WaitForCheesy(double delay) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
		this.delay = delay;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
		start = timeSinceInitialized();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
//        if (RobotMap.CheesyServer.getLeftCount() > MIN_COUNT || RobotMap.CheesyServer.getRightCount() > MIN_COUNT) 
		if (!(RobotMap.CheesyServer.getLeftStatus() || RobotMap.CheesyServer.getRightStatus()))
		{
            return true;
        }
        else
        {
			return (timeSinceInitialized()-start) > delay;
        }
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
